// array of products to be used
const productsArray = [
    {
        id: `rec43w3ipXvP28vog`,
        name: `Luffy Resin`,
        price: `35.99`,
        img: `/images/lupin resin.png`,
        category: `resin`,
        description: `Introducing the Resin Luffy Action Figure, a meticulously crafted collectible that captures the essence of Lupin, the beloved character, in stunning detail. This high-quality resin figure stands, showcasing Lupin's iconic charm and charisma.`,
        quantity: `1`,
    },
    {
        id: `rec4f2RIftFCb7aHh`,
        name: `Roronoa Zoro`,
        price: `35.99`,
        img: `/images/zoro.png`,
        category: `resin`,
        description: `Introducing the Zoro Action Figure, a dynamic and meticulously crafted collectible that pays homage to the legendary swordsman from one of anime and manga's most iconic series. Standing proudly, this finely detailed figure encapsulates the strength, determination, and unparalleled skill of Roronoa Zoro.`,
        quantity: `1`,
    },
    {
        id: `rec8kkCmSiMkbkiko`,
        name: `Nami`,
        price: `35.99`,
        img: `/images/Nami.png`,
        category: `resin`,
        description: `Introducing the Nami Action Figure, a captivating and finely detailed collectible that brings to life the charm and strength of one of anime's most beloved characters. Standing gracefully, this meticulously crafted figure captures the essence of Nami, the skilled navigator and heart of the Straw Hat Pirates.`,
        quantity: `1`,
    },
    {
        id: `recBohCqQsot4Q4II`,
        name: `Naruto`,
        price: `45.99`,
        img: `/images/Naruto.png`,
        category: `resin`,
        description: `Introducing the Naruto Action Figure, a stunning tribute to the iconic ninja and the hero of the Hidden Leaf Village. Standing strong, this meticulously crafted collectible captures the essence of Naruto Uzumaki, showcasing his determination, resilience, and unwavering ninja spirit.`,
        quantity: `1`,
    },
    {
        id: `recDG1JRZnbpRHpoy`,
        name: `Sabo`,
        price: `35.99`,
        img: `/images/Sabo.png`,
        category: `resin`,
        description: `Introducing the Sabo Action Figure, a striking homage to the fiery and formidable revolutionary from the world of One Piece. Standing proudly, this meticulously crafted collectible encapsulates the essence of Sabo, the sworn brother of Monkey D. Luffy and a key player in the battle against injustice.`,
        quantity: `1`,
    },
    {
        id: `recNWGyP7kjFhSqw3`,
        name: `Trafalgar Law`,
        price: `69.99`,
        img: `/images/Law.png`,
        category: `resin`,
        description: `Introducing the Trafalgar Law Action Figure, a meticulously crafted tribute to the enigmatic and powerful surgeon of death from the world of One Piece. Standing with commanding presence, this collectible masterpiece captures the essence of Trafalgar Law, showcasing his unique style, cunning intelligence, and formidable strength.`,
        quantity: `1`,
    },
    {
        id: `recZEougL5bbY4AEx`,
        name: `Goku`,
        price: `8.99`,
        img: `/images/Goku.png`,
        category: `resin`,
        description: `Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge`,
        quantity: `1`,
    },
    {
        id: `recjMK1jgTb2ld7sv`,
        name: `Tanjiro Kamado`,
        price: `50.99`,
        img: `/images/Tanjiro.png`,
        category: `resin`,
        description: `Introducing the Tanjiro Kamado Action Figure, a breathtaking tribute to the determined and compassionate demon slayer from the acclaimed series Demon Slayer: Kimetsu no Yaiba. Standing heroically, this meticulously crafted collectible encapsulates the essence of Tanjiro Kamado, showcasing his unwavering spirit, exceptional swordsmanship, and commitment to protecting humanity.`,
        quantity: `1`,
    },
    {
        id: `recmg2a1ctaEJNZhu`,
        name: `Gon`,
        price: `39.95`,
        img: `/images/gon.png`,
        category: `resin`,
        description: `
        Introducing the Gon Freecss Action Figure, a captivating tribute to the adventurous and determined young hunter from the critically acclaimed series, Hunter x Hunter. Standing boldly, this meticulously crafted collectible encapsulates the essence of Gon Freecss, showcasing his boundless enthusiasm, natural talent, and unwavering determination to become a true hunter.`,
        quantity: `1`,
    },
    {
        id: `recvKMNR3YFw0bEt3`,
        name: `Merlin`,
        price: `29.98`,
        img: `/images/Merlin.png`,
        category: `resin`,
        description: `Introducing the Merlin Action Figure, a spellbinding tribute to the enigmatic and powerful Caster-class servant from the acclaimed mobile game and anime series Fate/Grand Order. Standing majestically, this meticulously crafted collectible encapsulates the essence of Merlin, the legendary wizard and adviser, known for his magical prowess and charismatic presence.`,
        quantity: `1`,
    },
    {
        id: `recxaXFy5IW539sgM`,
        name: `Naruto Final Form`,
        price: `59.99`,
        img: `/images/Naruto Form.jpg`,
        category: `resin`,
        description: `Introducing the Naruto Last Final Form Action Figure, a breathtaking tribute to the culmination of Naruto Uzumaki's journey, capturing the power, determination, and iconic presence of the character's ultimate transformation. Standing boldly, this meticulously crafted collectible encapsulates the essence of Naruto in his most powerful state.`,
        quantity: `1`,
    },
    {
        id: `recyqtRglGNGtO4Q5`,
        name: `Tomie`,
        price: `30.99`,
        img: `/images/Tomie.png`,
        category: `resin`,
        description: `Introducing the Tomie Action Figure, a mesmerizing and unsettling tribute to the enigmatic and immortal beauty from the twisted imagination of horror manga maestro, Junji Ito. Standing hauntingly, this meticulously crafted collectible encapsulates the essence of Tomie, the beguiling yet malevolent character who has become a symbol of Ito's macabre storytelling.`,
        quantity: `1`,
    }
];

export { productsArray };